# UAV roles
ROLE_SURVEY = "SURVEY"
ROLE_RELAY = "RELAY"
ROLE_RESPONDER = "RESPONDER"
ROLE_RESERVE = "RESERVE"
ROLE_RETURN_HOME = "RETURN_HOME"

# UAV status
STATUS_ACTIVE = "ACTIVE"
STATUS_FAILED = "FAILED"
STATUS_RETURNING = "RETURNING"

# Mission status
MISSION_PENDING = "PENDING"
MISSION_ASSIGNED = "ASSIGNED"
MISSION_COMPLETED = "COMPLETED"

# Mission priority
PRIORITY_NORMAL = "NORMAL"
PRIORITY_HIGH = "HIGH"
PRIORITY_CRITICAL = "CRITICAL"